{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-frontend
  labels:
    {{- include "justbenchthatllm.frontend.labels" . | nindent 4 }}
  {{- if or .Values.global.annotations .Values.frontend.podAnnotations }}
  annotations:
    {{- include "justbenchthatllm.frontend.annotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "justbenchthatllm.frontend.selectorLabels" . | nindent 4 }}
{{- end }}

