{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-worker
  labels:
    {{- include "justbenchthatllm.worker.labels" . | nindent 4 }}
  {{- if or .Values.global.annotations .Values.worker.podAnnotations }}
  annotations:
    {{- include "justbenchthatllm.worker.annotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "justbenchthatllm.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "justbenchthatllm.worker.selectorLabels" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.global.annotations .Values.worker.podAnnotations }}
      annotations:
        {{- include "justbenchthatllm.worker.annotations" . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.worker.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.worker.pullSecret }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ include "justbenchthatllm.redis.url" . }}
        - name: MONGODB_URL
          value: {{ include "justbenchthatllm.mongo.url" . }}
        {{- range $key, $value := .Values.worker.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.worker.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml .Values.worker.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.worker.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml .Values.worker.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
{{- end }}

