{{- if .Values.pullSecret.create }}
{{- if and .Values.pullSecret.username .Values.pullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-pull-secret
  labels:
    {{- include "justbenchthatllm.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- else }}
{{- fail "pullSecret.create is true but pullSecret.username or pullSecret.password is not set" }}
{{- end }}
{{- end }}

{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.pullSecret.registry .Values.pullSecret.username .Values.pullSecret.password (printf "%s:%s" .Values.pullSecret.username .Values.pullSecret.password | b64enc) | b64enc }}
{{- end }}

