{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-backend
  labels:
    {{- include "justbenchthatllm.backend.labels" . | nindent 4 }}
  {{- if or .Values.global.annotations .Values.backend.podAnnotations }}
  annotations:
    {{- include "justbenchthatllm.backend.annotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "justbenchthatllm.backend.selectorLabels" . | nindent 4 }}
{{- end }}

