{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-mongo
  labels:
    {{- include "justbenchthatllm.mongo.labels" . | nindent 4 }}
  {{- if or .Values.global.annotations .Values.mongo.podAnnotations }}
  annotations:
    {{- include "justbenchthatllm.mongo.annotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "justbenchthatllm.mongo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "justbenchthatllm.fullname" . }}-mongo-headless
  labels:
    {{- include "justbenchthatllm.mongo.labels" . | nindent 4 }}
  {{- if or .Values.global.annotations .Values.mongo.podAnnotations }}
  annotations:
    {{- include "justbenchthatllm.mongo.annotations" . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "justbenchthatllm.mongo.selectorLabels" . | nindent 4 }}
{{- end }}

